# fly.toml for BACKEND (project-shortener)
app = 'project-shortener'
primary_region = 'syd'

[build]

[env]
  PORT = '8000'  # FastAPI default, matches CMD in Dockerfile

[http_service]
  internal_port = 8000  # ✅ Must match the PORT your FastAPI is listening on
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
source="shortener_data"
destination="/data"
