# fly.toml app configuration file generated for project-shortener on 2025-03-25T16:41:59+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-shortener'
primary_region = 'syd'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
